api_token_env: CROWDIN_PERSONAL_TOKEN
project_id: '468434'
preserve_hierarchy: true
files:
  - source: /core/components/minishop2/lexicon/en/*.inc.php
    translation: /core/components/minishop2/lexicon/%two_letters_code%/%original_file_name%
  - source: /docs/*.md
    translation: /docs/%two_letters_code%/%original_file_name%
    ignore:
      - /docs/index.md
